// ui/src/App.svelte
<script lang="ts">
  import {Route, Router} from "svelte-navigator";
  import Sidebar from "./components/Sidebar.svelte";
  import Keystores from "./pages/Keystores.svelte";
  import {keystores, getKeystores} from "./stores/keystores.ts";
  import {onMount} from 'svelte';
  import api from "./api";
  import LoginForm from "./components/LoginForm.svelte";
  import OnboardingForm from "./components/OnboardingForm.svelte";

  let onboarding = false;
  let ready = false;
  let login = false;

  let keystore = null;

  const healthCheck = () => {
    api.healthCheck().then(() => {
      console.log("Health check passed");
    }).catch(() => {
      console.log("Health check failed");
    });
  }

  // TODO: re-enable healthcheck
  // const interval = setInterval(healthCheck, 1000);
  // onDestroy(() => clearInterval(interval));

  function initialize() {
    // return $keystores;

    getKeystores().then((response) => {
      onboarding = response.length == 0;
      login = false

      if (response.length > 0) {
        //
        // keystores = response.sort((a, b) => {
        //   return a.id < b.id ? 1 : -1;
        // });

        keystore = response[0];
      }

    }).catch((error: Response) => {
      if (error.status == 401) {
        login = true;
        return
      }

      console.log(error)
    }).finally(() => {
      ready = true;
    });
  }

  onMount(async () => {
    initialize()
  });
</script>

<Router>
  {#if !ready}
    <span>Loading...</span>
  {:else}
    {#if onboarding}
      <OnboardingForm on:created={initialize} />
    {:else if login}
      <LoginForm on:login={initialize}/>
    {:else}
      <Sidebar keystores={$keystores}/>
      <main>
        <Route>
          <Keystores keystores={$keystores}/>
        </Route>

        <Route path="/keystore/:keystoreId">
          <Keystores keystores={$keystores}/>
        </Route>

        <Route path="/keystore/:keystoreId/entry/:entryId">
          <Keystores keystores={$keystores}/>
        </Route>
      </main>
    {/if}
  {/if}
</Router>

<style lang="scss">
  $bg: #0a0e11;
  //$bg: #111519;
  $accent: #00edb1;
  $text-color: #fff;

  @import url('https://rsms.me/inter/inter.css');

  :global {

    #app {
      height: 100%;
      display: flex;
      flex-direction: row;
      flex-grow: 1;
    }

    body {
      margin: 0;
      background-color: $bg;

      height: 100vh;
      max-height: 100vh;
      //max-height: -webkit-fill-available;
      //max-height: 100%;
    }

    * {
      font-family: 'Inter', sans-serif;
      font-weight: 300;
      font-size: 100%;
      color: $text-color;
      line-height: 1.4;
    }

    //::-webkit-scrollbar{
    //	width: 4px;
    //}
    //
    //::-webkit-scrollbar-track-piece{
    //	background-color: transparent;
    //}
    //
    //::-webkit-scrollbar-thumb{
    //	background-color: #363a41;
    //	border-radius: 2px;
    //}
    //
    //::-webkit-scrollbar-thumb:hover{
    //	background-color: #909090;
    //}
  }

  :root {
    color-scheme: dark;
  }

  main {
    display: flex;
    align-items: stretch;
    background-color: $bg;
    width: 100%;
  }
</style>

// ui/src/App.vue
<template>
	<span>{{ !ready ? 'Loading...' : '' }}</span>
	<InitializeKeystoreFullscreenModal v-if="onboarding" @created="keystoreCreated($event)"/>
	<Login v-if="login" @login="loggedIn()"/>

	<main v-if="keystores && keystore">
		<Sidebar/>
		<router-view/>
	</main>

	<!--	<transition>-->
<!--	<main>-->

<!--	</main>-->
	<!--			<Entries :is="Component" v-if="keystore" :entries="keystore.entries"/>-->
	<!--		</main>-->
	<!--	</transition>-->


	<!--	</router-view>-->


	<!--	<transition :duration="300" name="show">-->
	<!--		<main>-->
	<!--			<Sidebar v-if="keystores && keystore" :keystores="keystores" :keystore="keystore" />-->
	<!--			<router-view />-->
	<!--&lt;!&ndash;			<Entries></Entries>&ndash;&gt;-->
<!--&lt;!&ndash;			<Entry></Entry>&ndash;&gt;-->
<!--		</main>-->
<!--	</transition>-->
</template>

<script lang="ts">
import {defineComponent} from "vue";
import InitializeKeystoreFullscreenModal from "./components/InitializeKeystoreFullscreenModal.vue";
import Login from "./components/LoginForm.vue";
import api from "./api";
import {Keystore} from "./api/generated";
import Entries from "./components/Entries.vue";
import Entry from "./components/Entry.vue";
import Sidebar from "./components/Sidebar.vue";
import {useMainStore} from './store/'

export default defineComponent({
	setup() {
		const main = useMainStore()

		return {
			main,
		}
	},
	name: "App",
	components: {Sidebar, Entries, InitializeKeystoreFullscreenModal, Login, Entry},
	data(): {
		onboarding: boolean,
		login: boolean,
		ready: boolean,
		healthCheckIntervalId?: number,
	} {
		return {
			onboarding: false,
			login: false,
			ready: false,
		}
	},
	mounted() {
		if (this.$route.name !== "keystore") {
			this.$router.push({ name: 'keystore'})
		}

		this.healthCheckIntervalId = window.setInterval(this.healthCheck, 10000)
		this.ready = false

		this.init()
  },
	unmounted() {
		window.clearInterval(this.healthCheckIntervalId)
	},
	computed: {
		keystores(): Keystore[] {
			return this.main.keystores
		},
		keystore(): Keystore | undefined {
			return this.main.keystore
		},
	},
	watch: {
		$route(route) {
			if (route.params.keystoreId) {
				this.main.setKeystore(this.keystores.find(k => k.id === route.params.keystoreId))

				if (route.params.entryId) {
					this.main.setEntry(this.keystore?.entries.find(e => e.id === route.params.entryId))
				} else {
					this.main.setEntry(undefined)
				}
			} else {
				this.main.setKeystore(undefined)
			}
		},
	},
	methods: {
		healthCheck() {
			api.healthCheck()
		},
		init() {
			api.keystores().then((keystores) => {
				this.onboarding = keystores.length == 0;

				if (keystores.length > 0) {
					// keystores.push({
					// 	id: "1",
					// 	name: "Work",
					// 	entries: []
					// })
					// keystores.push({
					// 	id: "2",
					// 	name: "Old accounts",
					// 	entries: []
					// })

					this.main.setKeystores(keystores)
					this.main.setKeystore(keystores[0]);
					this.$router.push({ name: 'entries', params: { keystoreId: keystores[0].id }})
				}
			}).catch((error: Response) => {
				if (error.status == 401) {
					this.login = true;
					return
				}

				console.log(error)
			}).finally(() => {
				this.ready = true;
			});
		},
		keystoreCreated(keystore: Keystore) {
			this.onboarding = false;
			let keystores = [keystore]

			// keystores.push({
			// 	id: "1",
			// 	name: "Work",
			// 	entries: []
			// })
			// keystores.push({
			// 	id: "2",
			// 	name: "Old accounts",
			// 	entries: []
			// })

			this.main.setKeystores(keystores)
			this.main.setKeystore(keystores[0]);
		},
		loggedIn() {
			console.log("logged in");

			api.keystores().then((keystores) => {
				// keystores.push({
				// 	id: "1",
				// 	name: "Work",
				// 	entries: []
				// })
				// keystores.push({
				// 	id: "2",
				// 	name: "Old accounts",
				// 	entries: []
				// })

				this.main.setKeystores(keystores)
				this.main.setKeystore(keystores[0]);

				this.$router.push({ name: 'entries', params: { keystoreId: keystores[0].id }})
			}).catch(error => {
				console.log(error)
			}).finally(() => {
				this.login = false;
				// this.$router.push({ name: 'entries' })
			});
		}
	},
});
</script>

<style lang="scss">
$bg: #0a0e11;
//$bg: #111519;
$accent: #00edb1;
$text-color: #fff;

:root {
	color-scheme: dark;
}

html, body {
	//height: 100%;
	//overflow: hidden
}

html {
	//height: -webkit-fill-available;
}
body {
	margin: 0;
	background-color: $bg;

	height: 100vh;
	max-height: 100vh;
	//max-height: -webkit-fill-available;
	//max-height: 100%;
}

main {
	display: flex;
	align-items: stretch;
	background-color: $bg;
	width: 100%;
}

@import url('https://rsms.me/inter/inter.css');

* {
	font-family: 'Inter', sans-serif;
	font-weight: 300;
	font-size: 100%;
	color: $text-color;
	line-height: 1.4;
}

*::-webkit-scrollbar {
	width: 0;
	display: none;
	background: transparent;
}

* {
	scrollbar-width: none;
	-ms-overflow-style: none;
}

//::-webkit-scrollbar{
//	width: 4px;
//}
//
//::-webkit-scrollbar-track-piece{
//	background-color: transparent;
//}
//
//::-webkit-scrollbar-thumb{
//	background-color: #363a41;
//	border-radius: 2px;
//}
//
//::-webkit-scrollbar-thumb:hover{
//	background-color: #909090;
//}

#app {
	height: 100%;
	display: flex;
	flex-direction: row;
	flex-grow: 1;
}

.show-enter-active, .show-leave-active {
	transition: .3s;
}

.show-enter-from {
	opacity: 0;
	transform: scale(.98);
}

.show-enter-to {
	opacity: 1;
	transform: scale(1);
}

.show-leave-from {
	opacity: 1;
	transform: scale(1);
}

.show-leave-to {
	opacity: 0;
	transform: scale(.98);
}
</style>
